### ISSUE TITLE
Incorrect color values

### ISSUE THREAD

**Issue by iamthad** [belak/base16-builder-go#4]
The builder is producing incorrect values in some cases. Here's an example from `windows-command-prompt/base16-3024.reg`:

```diff
-"ColorTable10"=dword:0043454a ; base02
+"ColorTable10"=dword:00434549 ; base02
```

Whereas `3024.yaml` contains the following:
```yaml
base02: "4a4543" #  --
```

**Comment by belak** [comment]
That is very strange but I'm seeing the same thing... for some reason only in the builder templates. I'm guessing there must be a bug in my hex conversion.

Also, they should be padded and aren't currently.

**Comment by belak** [comment]
It looks like there's a bug in the color conversion library I'm using (which isn't strictly needed because it was originally added to deal with HSV - a color space we're not supporting any more). I've filed a bug (https://github.com/lucasb-eyer/go-colorful/issues/12) and will look at either patching their library or switching to parsing the hex values myself if it's not needed any more.

**Comment by belak** [comment]
I've fixed the two issues (incorrect values and non-padded hex strings) in the latest two commits. Please let me know if you have any further issues. Thanks for the report!

**Comment by belak** [comment]
I've also opened https://github.com/lucasb-eyer/go-colorful/pull/13 to fix the issue with the library we were using.
